package infrastructure

import (
	"time"

	"speech-practice-app/internal/domain"
)

// seedMouthExercisesExtended returns mouth exercises me-006 through me-055.
func seedMouthExercisesExtended(now time.Time) []domain.Exercise {
	return []domain.Exercise{
		// Lips - beginner
		{ID: "me-006", Name: "Lip Stretch", Description: "Stretch lips wide to improve lip mobility", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationLips}, Duration: 60 * time.Second, Repetitions: 10, Instructions: "Stretch lips into a wide smile, hold 3 seconds, then relax. Repeat.", PhoneticGuidance: "Feel the corners of your mouth pulling outward", CreatedAt: now, UpdatedAt: now},
		{ID: "me-007", Name: "Lip Trill", Description: "Vibrate lips together for warm-up", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationLips}, Duration: 60 * time.Second, Repetitions: 8, Instructions: "Blow air through loosely closed lips to create a trill. Sustain for 5 seconds.", PhoneticGuidance: "Keep lips relaxed, let air do the work", CreatedAt: now, UpdatedAt: now},
		{ID: "me-008", Name: "Lip Pop", Description: "Practice lip closure and release for plosive sounds", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationLips}, Duration: 45 * time.Second, Repetitions: 15, Instructions: "Press lips together firmly, build pressure, then release with a pop sound.", PhoneticGuidance: "Like saying 'p' or 'b' in isolation", CreatedAt: now, UpdatedAt: now},
		{ID: "me-009", Name: "Lip Pucker and Spread", Description: "Alternate between puckered and spread lip positions", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationLips}, Duration: 60 * time.Second, Repetitions: 12, Instructions: "Pucker lips as if kissing, then spread wide into a smile. Alternate rapidly.", PhoneticGuidance: "Exaggerate each position for maximum benefit", CreatedAt: now, UpdatedAt: now},
		{ID: "me-010", Name: "Lip Massage", Description: "Relax lip muscles with gentle massage movements", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationLips}, Duration: 60 * time.Second, Repetitions: 5, Instructions: "Use fingertips to gently massage upper and lower lips in circular motions.", PhoneticGuidance: "Relax completely, let tension release", CreatedAt: now, UpdatedAt: now},
		// Lips - intermediate
		{ID: "me-011", Name: "Lip Isolation Drill", Description: "Move upper and lower lips independently", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationLips}, Duration: 90 * time.Second, Repetitions: 10, Instructions: "Try to move only the upper lip upward while keeping the lower lip still. Then reverse.", PhoneticGuidance: "Isolate each lip independently", CreatedAt: now, UpdatedAt: now},
		{ID: "me-012", Name: "Bilabial Sound Series", Description: "Practice all bilabial sounds in sequence", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationLips}, Duration: 90 * time.Second, Repetitions: 8, Instructions: "Say 'pa-ba-ma-wa' in sequence, focusing on lip contact for each sound.", PhoneticGuidance: "P and B need firm lip closure; M needs nasal resonance", CreatedAt: now, UpdatedAt: now},
		// Lips - advanced
		{ID: "me-013", Name: "Rapid Lip Alternation", Description: "Rapidly alternate between multiple lip positions", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyAdvanced, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationLips}, Duration: 120 * time.Second, Repetitions: 10, Instructions: "Cycle through pucker, spread, round, and neutral positions as fast as possible.", PhoneticGuidance: "Maintain clarity at high speed", CreatedAt: now, UpdatedAt: now},
		// Teeth - beginner
		{ID: "me-014", Name: "Teeth Clicking", Description: "Practice dental contact for dental sounds", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTeeth}, Duration: 45 * time.Second, Repetitions: 15, Instructions: "Gently click upper and lower teeth together rhythmically. Focus on even contact.", PhoneticGuidance: "Light contact only, do not clench", CreatedAt: now, UpdatedAt: now},
		{ID: "me-015", Name: "Dental Fricative Practice", Description: "Practice tongue-to-teeth contact for TH sounds", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTeeth, domain.ArticulationTongueTip}, Duration: 60 * time.Second, Repetitions: 12, Instructions: "Place tongue tip lightly between teeth and blow air. Feel the friction.", PhoneticGuidance: "Tongue barely touches teeth, air flows over it", CreatedAt: now, UpdatedAt: now},
		{ID: "me-016", Name: "Labiodental Contact", Description: "Practice upper teeth to lower lip contact", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTeeth, domain.ArticulationLips}, Duration: 60 * time.Second, Repetitions: 10, Instructions: "Rest upper teeth lightly on lower lip. Say 'f' and 'v' sounds repeatedly.", PhoneticGuidance: "Upper teeth rest on inner edge of lower lip", CreatedAt: now, UpdatedAt: now},
		// Teeth - intermediate
		{ID: "me-017", Name: "Dental Sound Contrast", Description: "Contrast dental and alveolar sounds", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTeeth, domain.ArticulationTongueTip}, Duration: 90 * time.Second, Repetitions: 8, Instructions: "Alternate between 'th' (dental) and 't' (alveolar) sounds. Notice tongue position difference.", PhoneticGuidance: "TH: tongue between teeth; T: tongue behind teeth", CreatedAt: now, UpdatedAt: now},
		// Tongue tip - beginner
		{ID: "me-018", Name: "Tongue Tip Taps", Description: "Rapid tongue tip tapping for alveolar sounds", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueTip}, Duration: 60 * time.Second, Repetitions: 20, Instructions: "Tap tongue tip rapidly against the ridge behind upper teeth. Say 'da-da-da'.", PhoneticGuidance: "Light, quick taps on the alveolar ridge", CreatedAt: now, UpdatedAt: now},
		{ID: "me-019", Name: "Tongue Tip Circles", Description: "Circular tongue tip movements for flexibility", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueTip}, Duration: 60 * time.Second, Repetitions: 10, Instructions: "Move tongue tip in circles along the inside of your lips. Go clockwise then counter-clockwise.", PhoneticGuidance: "Keep tongue tip pointed throughout", CreatedAt: now, UpdatedAt: now},
		{ID: "me-020", Name: "Tongue Tip Reach", Description: "Extend tongue tip as far as possible", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueTip}, Duration: 45 * time.Second, Repetitions: 10, Instructions: "Extend tongue tip out and down toward chin, then up toward nose. Hold each position.", PhoneticGuidance: "Keep tongue tip pointed, not flat", CreatedAt: now, UpdatedAt: now},
		// Tongue tip - intermediate
		{ID: "me-021", Name: "Alveolar Sound Drill", Description: "Practice all alveolar consonants in sequence", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueTip}, Duration: 90 * time.Second, Repetitions: 8, Instructions: "Say 't-d-n-l-s-z' in sequence, focusing on tongue tip placement for each.", PhoneticGuidance: "All these sounds use the alveolar ridge behind upper teeth", CreatedAt: now, UpdatedAt: now},
		{ID: "me-022", Name: "Tongue Tip Precision", Description: "Precise tongue tip placement exercises", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueTip}, Duration: 90 * time.Second, Repetitions: 10, Instructions: "Touch tongue tip to specific spots: behind upper teeth, alveolar ridge, hard palate. Hold each.", PhoneticGuidance: "Precision matters more than speed", CreatedAt: now, UpdatedAt: now},
		// Tongue tip - advanced
		{ID: "me-023", Name: "Tongue Tip Trill", Description: "Produce a rolled R using tongue tip vibration", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyAdvanced, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueTip}, Duration: 120 * time.Second, Repetitions: 8, Instructions: "Place tongue tip at alveolar ridge and blow air to create a trill. Sustain for 3 seconds.", PhoneticGuidance: "Tongue tip must be relaxed to vibrate freely", CreatedAt: now, UpdatedAt: now},
		{ID: "me-024", Name: "Retroflex Tongue Position", Description: "Practice retroflex tongue position for R sounds", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyAdvanced, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueTip}, Duration: 90 * time.Second, Repetitions: 10, Instructions: "Curl tongue tip back toward hard palate without touching. Hold position and say 'er'.", PhoneticGuidance: "Tongue tip curls back, sides touch upper molars", CreatedAt: now, UpdatedAt: now},
		// Tongue blade - beginner
		{ID: "me-025", Name: "Tongue Blade Press", Description: "Press tongue blade against palate for strength", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueBlade}, Duration: 60 * time.Second, Repetitions: 10, Instructions: "Press the flat middle part of your tongue firmly against the roof of your mouth. Hold 3 seconds.", PhoneticGuidance: "Feel the broad contact of tongue blade on palate", CreatedAt: now, UpdatedAt: now},
		{ID: "me-026", Name: "Lateral Tongue Movement", Description: "Move tongue blade side to side", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueBlade}, Duration: 60 * time.Second, Repetitions: 12, Instructions: "Move tongue blade from left to right inside your mouth, touching each cheek.", PhoneticGuidance: "Keep tongue flat and broad during movement", CreatedAt: now, UpdatedAt: now},
		// Tongue blade - intermediate
		{ID: "me-027", Name: "Palatal Sound Practice", Description: "Practice palatal consonants using tongue blade", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueBlade}, Duration: 90 * time.Second, Repetitions: 8, Instructions: "Say 'sh-zh-ch-j' sounds, feeling tongue blade rise toward palate for each.", PhoneticGuidance: "Tongue blade arches up toward hard palate", CreatedAt: now, UpdatedAt: now},
		{ID: "me-028", Name: "Tongue Blade Groove", Description: "Form a groove in tongue blade for sibilant sounds", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueBlade}, Duration: 90 * time.Second, Repetitions: 10, Instructions: "Form a narrow groove down the center of your tongue blade. Direct air through the groove.", PhoneticGuidance: "The groove channels air for S and Z sounds", CreatedAt: now, UpdatedAt: now},
		// Tongue blade - advanced
		{ID: "me-029", Name: "Tongue Blade Isolation", Description: "Move tongue blade independently of tongue tip", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyAdvanced, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueBlade}, Duration: 120 * time.Second, Repetitions: 8, Instructions: "Keep tongue tip still while raising and lowering tongue blade. Requires fine motor control.", PhoneticGuidance: "Isolate blade movement from tip movement", CreatedAt: now, UpdatedAt: now},
		// Tongue back - beginner
		{ID: "me-030", Name: "Tongue Back Humming", Description: "Activate tongue back with humming exercises", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueBack}, Duration: 60 * time.Second, Repetitions: 8, Instructions: "Hum with mouth closed, feeling vibration at back of tongue. Vary pitch up and down.", PhoneticGuidance: "Feel the back of tongue vibrate against soft palate", CreatedAt: now, UpdatedAt: now},
		{ID: "me-031", Name: "Velar Sound Introduction", Description: "Practice basic velar consonants", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueBack}, Duration: 60 * time.Second, Repetitions: 12, Instructions: "Say 'k-g-ng' sounds repeatedly, feeling tongue back contact with soft palate.", PhoneticGuidance: "Back of tongue touches soft palate for K and G", CreatedAt: now, UpdatedAt: now},
		// Tongue back - intermediate
		{ID: "me-032", Name: "Velar Contrast Drill", Description: "Contrast voiced and voiceless velar sounds", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueBack}, Duration: 90 * time.Second, Repetitions: 10, Instructions: "Alternate between 'k' (voiceless) and 'g' (voiced). Feel the difference in vocal cord vibration.", PhoneticGuidance: "Same tongue position, different voicing", CreatedAt: now, UpdatedAt: now},
		{ID: "me-033", Name: "Tongue Back Strength", Description: "Build tongue back strength for clear velar sounds", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueBack}, Duration: 90 * time.Second, Repetitions: 10, Instructions: "Press tongue back firmly against soft palate, hold 3 seconds, release. Repeat.", PhoneticGuidance: "Strong contact produces clear K and G sounds", CreatedAt: now, UpdatedAt: now},
		// Tongue back - advanced
		{ID: "me-034", Name: "Uvular Sound Exploration", Description: "Explore uvular articulation for advanced speakers", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyAdvanced, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueBack, domain.ArticulationSoftPalate}, Duration: 120 * time.Second, Repetitions: 6, Instructions: "Gargle gently to feel uvula vibration. Then try to produce a uvular trill.", PhoneticGuidance: "Tongue back contacts uvula, not soft palate", CreatedAt: now, UpdatedAt: now},
		// Soft palate - beginner
		{ID: "me-035", Name: "Soft Palate Yawn", Description: "Open soft palate with yawning motion", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationSoftPalate}, Duration: 60 * time.Second, Repetitions: 8, Instructions: "Simulate a yawn to feel soft palate rise. Hold the open position for 3 seconds.", PhoneticGuidance: "Feel the back of your mouth open up", CreatedAt: now, UpdatedAt: now},
		{ID: "me-036", Name: "Nasal Resonance Exercise", Description: "Direct sound through nasal cavity", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationSoftPalate}, Duration: 60 * time.Second, Repetitions: 8, Instructions: "Say 'mmm' and 'nnn' sounds, feeling vibration in your nose. Then switch to oral sounds.", PhoneticGuidance: "Soft palate lowers for nasal sounds, raises for oral", CreatedAt: now, UpdatedAt: now},
		// Soft palate - intermediate
		{ID: "me-037", Name: "Velopharyngeal Control", Description: "Control soft palate closure for oral sounds", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationSoftPalate}, Duration: 90 * time.Second, Repetitions: 8, Instructions: "Alternate between nasal 'm' and oral 'b' sounds. Feel soft palate move up and down.", PhoneticGuidance: "Soft palate must close completely for oral sounds", CreatedAt: now, UpdatedAt: now},
		{ID: "me-038", Name: "Palatal Arch Opening", Description: "Widen the palatal arch for better resonance", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationSoftPalate}, Duration: 90 * time.Second, Repetitions: 8, Instructions: "Open mouth wide and try to widen the back of your mouth. Say 'ah' with maximum openness.", PhoneticGuidance: "Imagine a ball in the back of your mouth", CreatedAt: now, UpdatedAt: now},
		// Soft palate - advanced
		{ID: "me-039", Name: "Soft Palate Rapid Switching", Description: "Rapidly switch between nasal and oral resonance", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyAdvanced, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationSoftPalate}, Duration: 120 * time.Second, Repetitions: 10, Instructions: "Rapidly alternate 'ma-ba-na-da' sequences. Soft palate must switch quickly.", PhoneticGuidance: "Speed requires automatic soft palate control", CreatedAt: now, UpdatedAt: now},
		// Jaw - beginner
		{ID: "me-040", Name: "Jaw Circles", Description: "Circular jaw movements for flexibility", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationJaw}, Duration: 60 * time.Second, Repetitions: 8, Instructions: "Move jaw in slow circles: forward, down, back, up. Reverse direction.", PhoneticGuidance: "Keep movements smooth and pain-free", CreatedAt: now, UpdatedAt: now},
		{ID: "me-041", Name: "Jaw Drop", Description: "Maximum jaw opening for open vowels", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationJaw}, Duration: 60 * time.Second, Repetitions: 10, Instructions: "Drop jaw as far as comfortable, hold 3 seconds, close slowly. Say 'ah' at maximum opening.", PhoneticGuidance: "Jaw drops, not head tilts back", CreatedAt: now, UpdatedAt: now},
		{ID: "me-042", Name: "Jaw Resistance Training", Description: "Build jaw strength with resistance", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationJaw}, Duration: 60 * time.Second, Repetitions: 10, Instructions: "Place fist under chin and try to open mouth against gentle resistance. Hold 3 seconds.", PhoneticGuidance: "Gentle resistance only, no pain", CreatedAt: now, UpdatedAt: now},
		// Jaw - intermediate
		{ID: "me-043", Name: "Jaw Protrusion", Description: "Move jaw forward and back for flexibility", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationJaw}, Duration: 90 * time.Second, Repetitions: 10, Instructions: "Push jaw forward as far as comfortable, hold, then pull back. Repeat.", PhoneticGuidance: "Controlled movement, no clicking or pain", CreatedAt: now, UpdatedAt: now},
		{ID: "me-044", Name: "Jaw Lateral Glide", Description: "Side-to-side jaw movements", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationJaw}, Duration: 90 * time.Second, Repetitions: 12, Instructions: "Slide jaw to the left, hold, center, then right, hold. Keep teeth slightly apart.", PhoneticGuidance: "Smooth gliding motion, no jerking", CreatedAt: now, UpdatedAt: now},
		// Jaw - advanced
		{ID: "me-045", Name: "Jaw Independence Drill", Description: "Move jaw independently of tongue and lips", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyAdvanced, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationJaw}, Duration: 120 * time.Second, Repetitions: 8, Instructions: "Open and close jaw while keeping tongue and lips completely still. Then add tongue movement.", PhoneticGuidance: "Jaw, tongue, and lips should be able to move independently", CreatedAt: now, UpdatedAt: now},
		// Mixed articulation - beginner
		{ID: "me-046", Name: "Full Mouth Warm-Up", Description: "Comprehensive warm-up for all articulators", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationLips, domain.ArticulationJaw, domain.ArticulationTongueTip}, Duration: 120 * time.Second, Repetitions: 3, Instructions: "Sequence: lip trill, jaw circles, tongue tip taps, soft palate yawn. One minute each.", PhoneticGuidance: "Warm up all articulators before speaking", CreatedAt: now, UpdatedAt: now},
		{ID: "me-047", Name: "Vowel Shaping", Description: "Practice precise vowel mouth shapes", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyBeginner, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationLips, domain.ArticulationJaw}, Duration: 90 * time.Second, Repetitions: 10, Instructions: "Say each vowel (a-e-i-o-u) with exaggerated mouth shapes. Hold each for 2 seconds.", PhoneticGuidance: "Each vowel has a unique lip and jaw position", CreatedAt: now, UpdatedAt: now},
		// Mixed articulation - intermediate
		{ID: "me-048", Name: "Consonant Cluster Prep", Description: "Prepare articulators for consonant clusters", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueTip, domain.ArticulationTongueBlade, domain.ArticulationLips}, Duration: 90 * time.Second, Repetitions: 8, Instructions: "Practice 'str', 'spl', 'scr' clusters slowly, then speed up. Focus on smooth transitions.", PhoneticGuidance: "Each articulator must move precisely and quickly", CreatedAt: now, UpdatedAt: now},
		{ID: "me-049", Name: "Articulator Coordination", Description: "Coordinate all articulators for complex sounds", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyIntermediate, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationLips, domain.ArticulationTongueTip, domain.ArticulationJaw}, Duration: 90 * time.Second, Repetitions: 8, Instructions: "Say 'la-ra-wa-ya' sequence. Each sound requires different articulator coordination.", PhoneticGuidance: "Notice how lips, tongue, and jaw work together", CreatedAt: now, UpdatedAt: now},
		// Mixed articulation - advanced
		{ID: "me-050", Name: "Rapid Articulator Switching", Description: "Switch rapidly between different articulation points", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyAdvanced, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationLips, domain.ArticulationTeeth, domain.ArticulationTongueTip, domain.ArticulationTongueBlade, domain.ArticulationTongueBack}, Duration: 120 * time.Second, Repetitions: 6, Instructions: "Say 'pa-fa-ta-sha-ka' rapidly. Each syllable uses a different articulation point.", PhoneticGuidance: "Smooth, rapid transitions between articulation points", CreatedAt: now, UpdatedAt: now},
		{ID: "me-051", Name: "Tongue Tip to Back Sweep", Description: "Sweep tongue from tip to back in one motion", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyAdvanced, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueTip, domain.ArticulationTongueBlade, domain.ArticulationTongueBack}, Duration: 120 * time.Second, Repetitions: 10, Instructions: "Touch tongue tip to upper teeth, then sweep back along palate to soft palate. Reverse.", PhoneticGuidance: "Smooth continuous motion along the palate", CreatedAt: now, UpdatedAt: now},
		{ID: "me-052", Name: "Precision Articulation Circuit", Description: "Circuit training for all articulation points", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyAdvanced, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationLips, domain.ArticulationTeeth, domain.ArticulationTongueTip, domain.ArticulationTongueBlade, domain.ArticulationTongueBack, domain.ArticulationSoftPalate, domain.ArticulationJaw}, Duration: 120 * time.Second, Repetitions: 3, Instructions: "30 seconds each: lip trills, dental fricatives, tongue tip taps, blade presses, velar sounds, palate yawns, jaw circles.", PhoneticGuidance: "Full articulator workout", CreatedAt: now, UpdatedAt: now},
		{ID: "me-053", Name: "Minimal Pair Articulation", Description: "Practice minimal pairs to sharpen articulation", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyAdvanced, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueTip, domain.ArticulationTeeth}, Duration: 120 * time.Second, Repetitions: 8, Instructions: "Say minimal pairs: 'thin/tin', 'then/den', 'three/tree'. Focus on precise articulation differences.", PhoneticGuidance: "Small articulation differences change meaning", CreatedAt: now, UpdatedAt: now},
		{ID: "me-054", Name: "Tongue Strength Circuit", Description: "Build overall tongue strength and endurance", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyAdvanced, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationTongueTip, domain.ArticulationTongueBlade, domain.ArticulationTongueBack}, Duration: 120 * time.Second, Repetitions: 5, Instructions: "Hold tongue tip up 10s, blade up 10s, back up 10s. Repeat circuit.", PhoneticGuidance: "Build endurance for sustained speech", CreatedAt: now, UpdatedAt: now},
		{ID: "me-055", Name: "Dynamic Articulation Flow", Description: "Fluid movement through all articulation positions", Category: domain.CategoryMouthExercise, Difficulty: domain.DifficultyAdvanced, ArticulationPoints: []domain.ArticulationPoint{domain.ArticulationLips, domain.ArticulationTongueTip, domain.ArticulationTongueBlade, domain.ArticulationTongueBack, domain.ArticulationSoftPalate, domain.ArticulationJaw}, Duration: 120 * time.Second, Repetitions: 4, Instructions: "Say 'ma-na-la-ra-ya-wa' in a flowing sequence. Focus on smooth transitions between all positions.", PhoneticGuidance: "Articulators should flow, not jump", CreatedAt: now, UpdatedAt: now},
	}
}
