package infrastructure

import (
	"time"

	"speech-practice-app/internal/domain"
)

// seedTongueTwistersExtended returns tongue twister exercises tt-006 through tt-105.
func seedTongueTwistersExtended(now time.Time) []domain.Exercise {
	return []domain.Exercise{
		// /s/ SoundS — 10 twisters
		{ID: "tt-006", Name: "Six Slippery Snails", Description: "S sound tongue twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundS}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Six slippery snails slid slowly seaward' slowly, then increase speed.", PhoneticGuidance: "Keep tongue behind upper teeth, direct air through the narrow gap", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-007", Name: "Sally Sells Seashells", Description: "S sound classic twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundS}, Duration: 25 * time.Second, Repetitions: 5, Instructions: "Say 'Sally sells seashells by the seashore' three times in a row.", PhoneticGuidance: "Crisp S at the start of each word", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-008", Name: "Silly Sally Sheep", Description: "S sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundS}, Duration: 25 * time.Second, Repetitions: 5, Instructions: "Say 'Silly Sally swiftly shooed seven silly sheep' clearly.", PhoneticGuidance: "Distinguish S from SH — tongue position shifts for each", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-009", Name: "Susie Shoeshine", Description: "S sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundS}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Susie works in a shoeshine shop where she shines and shapes and shaves' clearly.", PhoneticGuidance: "Alternate between S and SH sounds deliberately", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-010", Name: "Sam's Short Socks", Description: "S sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundS}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Sam's shop stocks short spotted socks' five times.", PhoneticGuidance: "Short, sharp S sounds — keep tongue steady", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-011", Name: "Sister Susie Sewing", Description: "S sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundS}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Sister Susie sewing shirts for soldiers' repeatedly.", PhoneticGuidance: "Sustain the S sound at the start of each word", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-012", Name: "Selfish Shellfish", Description: "S and SH contrast twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundS, domain.SoundSH}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Selfish shellfish sell shellfish' as fast as possible.", PhoneticGuidance: "S: tongue behind teeth; SH: tongue pulled back slightly", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-013", Name: "Seven Slick Snakes", Description: "S sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundS}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Seven slick slippery snakes slowly sliding southward' at speed.", PhoneticGuidance: "Maintain crisp S through consonant clusters", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-014", Name: "Sing a Song of Sixpence", Description: "S sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundS}, Duration: 25 * time.Second, Repetitions: 5, Instructions: "Say 'Sing a song of sixpence, a pocket full of rye' clearly.", PhoneticGuidance: "Soft S at the start, sustain through the phrase", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-015", Name: "Sly Sam Slurps", Description: "S sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundS}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Sly Sam slurps Sally's soup' five times quickly.", PhoneticGuidance: "S blends with L — keep tongue tip precise", CreatedAt: now, UpdatedAt: now},

		// /z/ SoundZ — 10 twisters
		{ID: "tt-016", Name: "Fuzzy Wuzzy Bear", Description: "Z sound classic twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundZ}, Duration: 25 * time.Second, Repetitions: 5, Instructions: "Say 'Fuzzy Wuzzy was a bear, Fuzzy Wuzzy had no hair' clearly.", PhoneticGuidance: "Z is a voiced S — add vocal cord vibration", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-017", Name: "Zebras Zig and Zag", Description: "Z sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundZ}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Zebras zig and zag across the zoo' five times.", PhoneticGuidance: "Strong Z at the start of each word", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-018", Name: "Zizzy Zappy Zoo", Description: "Z sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundZ}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Zizzy zappy zippy zoo' as fast as you can.", PhoneticGuidance: "Buzz the Z sound — feel vibration in your teeth", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-019", Name: "Zero Zebras", Description: "Z sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundZ}, Duration: 25 * time.Second, Repetitions: 5, Instructions: "Say 'Zero zebras at the zoo zone' repeatedly.", PhoneticGuidance: "Z at word start — voiced and buzzy", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-020", Name: "Buzzing Bees", Description: "Z sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundZ}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Buzzing bees buzz busily beside the buzzing beehive' clearly.", PhoneticGuidance: "Z in the middle of words — sustain the buzz", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-021", Name: "Lazy Lizards", Description: "Z sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundZ}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Lazy lizards lying lazily in the hazy sunshine' five times.", PhoneticGuidance: "Z in the middle — voiced and relaxed", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-022", Name: "Zigzag Zinc Fences", Description: "Z sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundZ}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Zigzag zinc fences zip and zap' repeatedly.", PhoneticGuidance: "Z in clusters — maintain voicing throughout", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-023", Name: "Zoe's Zero Zones", Description: "Z sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundZ}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Zoe's zone has zero zones with zeal' as fast as possible.", PhoneticGuidance: "Multiple Z sounds — keep each one voiced", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-024", Name: "Buzzy Bees in a Breeze", Description: "Z sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundZ}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Buzzy bees in a breeze buzz and wheeze with ease' quickly.", PhoneticGuidance: "Z at end of words — don't devoice it", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-025", Name: "Fizzing Fizzy Drinks", Description: "Z sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundZ}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Fizzing fizzy drinks fizzle and sizzle' at speed.", PhoneticGuidance: "Z in the middle and end — sustain voicing", CreatedAt: now, UpdatedAt: now},

		// /r/ SoundR — 10 twisters
		{ID: "tt-026", Name: "Round the Rugged Rock", Description: "R sound classic twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundR}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Round the rugged rock the ragged rascal ran' three times.", PhoneticGuidance: "Curl tongue back slightly for American R", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-027", Name: "Rubber Baby Buggy Bumpers", Description: "R and B sound twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundR}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Rubber baby buggy bumpers' five times quickly.", PhoneticGuidance: "R before vowels — tongue curls back then releases", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-028", Name: "Really Leery Rarely", Description: "R and L contrast twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundR, domain.SoundL}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Really leery rarely relies on Larry' at speed.", PhoneticGuidance: "R: tongue curls back; L: tongue tip touches ridge", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-029", Name: "Robert Rowley Rolled", Description: "R sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundR}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Robert Rowley rolled a round roll round a round roll' clearly.", PhoneticGuidance: "R at word start — strong retroflex position", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-030", Name: "Rory the Warrior", Description: "R sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundR}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Rory the warrior and Roger the worrier were rarely weary' clearly.", PhoneticGuidance: "R in different positions — initial, medial, final", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-031", Name: "Rush the Washing Russell", Description: "R sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundR}, Duration: 25 * time.Second, Repetitions: 5, Instructions: "Say 'Rush the washing Russell' ten times.", PhoneticGuidance: "Short phrase — focus on clean R each time", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-032", Name: "Rare Red Roses", Description: "R sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundR}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Rare red roses run rapidly round the river' clearly.", PhoneticGuidance: "R before different vowels — adjust tongue slightly", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-033", Name: "Ripe White Wheat Reapers", Description: "R sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundR}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Ripe white wheat reapers reap ripe white wheat right' clearly.", PhoneticGuidance: "R at word start — consistent retroflex position", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-034", Name: "River Road Runs Rapidly", Description: "R sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundR}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'River road runs rapidly round the ridge' five times.", PhoneticGuidance: "R in initial position — strong and clear", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-035", Name: "Red Roses Rarely Rust", Description: "R sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundR}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Red roses rarely rust, but rusty roses rarely remain red' at speed.", PhoneticGuidance: "R in clusters and final position — maintain quality", CreatedAt: now, UpdatedAt: now},

		// /l/ SoundL — 10 twisters
		{ID: "tt-036", Name: "Lily Loves Lollipops", Description: "L sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundL}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Lily loves lollipops, lollipops Lily loves' five times.", PhoneticGuidance: "Tongue tip touches alveolar ridge for L", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-037", Name: "Lemon Liniment", Description: "L sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundL}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Lovely lemon liniment' ten times.", PhoneticGuidance: "L before different vowels — tongue tip stays on ridge", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-038", Name: "Luke Luck Likes Lakes", Description: "L sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundL}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Luke Luck likes lakes, Luke's duck likes lakes' clearly.", PhoneticGuidance: "L at word start — clear tongue tip contact", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-039", Name: "Lola Loves Lollies", Description: "L sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundL}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Lola loves lollies, lollies Lola loves' five times.", PhoneticGuidance: "L in initial and medial positions", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-040", Name: "Lily Lamont Lemon", Description: "L sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundL}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Lily Lamont loves lemon lollipops and lollies' clearly.", PhoneticGuidance: "Multiple L sounds — keep tongue tip active", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-041", Name: "Lively Lads Love Larks", Description: "L sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundL}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Lively lads love lively larks leaping lightly' clearly.", PhoneticGuidance: "L before different consonants — maintain clarity", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-042", Name: "Luscious Lemons Linger", Description: "L sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundL}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Luscious lemons linger long on the lemon tree' five times.", PhoneticGuidance: "L in clusters — don't drop the tongue contact", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-043", Name: "Lola Laughed Loudly", Description: "L sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundL}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Lola laughed loudly at the lively little llama' at speed.", PhoneticGuidance: "L in all positions — initial, medial, final", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-044", Name: "Lively Little Lions", Description: "L sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundL}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Lively little lions lie lazily licking lollipops' quickly.", PhoneticGuidance: "L in clusters and final position — full tongue contact", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-045", Name: "Lateral L Drill", Description: "L sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundL}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Lateral L allows lateral airflow along the lateral sides' at speed.", PhoneticGuidance: "Air flows around the sides of the tongue for L", CreatedAt: now, UpdatedAt: now},

		// /th/ SoundTH — 10 twisters
		{ID: "tt-046", Name: "Thirty-Three Thieves", Description: "TH sound classic twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundTH}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'The thirty-three thieves thought they thrilled the throne throughout Thursday' clearly.", PhoneticGuidance: "Tongue between teeth for TH — voiced and voiceless", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-047", Name: "Whether the Weather", Description: "TH sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundTH}, Duration: 25 * time.Second, Repetitions: 5, Instructions: "Say 'Whether the weather be fine or whether the weather be not' clearly.", PhoneticGuidance: "Voiced TH in 'whether' — tongue between teeth with voice", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-048", Name: "Theophilus Thistle", Description: "TH sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundTH}, Duration: 40 * time.Second, Repetitions: 3, Instructions: "Say 'Theophilus Thistle the thistle sifter sifted a sieve of unsifted thistles' clearly.", PhoneticGuidance: "Voiceless TH — tongue lightly between teeth, no voice", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-049", Name: "Three Thin Thinkers", Description: "TH sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundTH}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Three thin thinkers thinking thick thoughtful thoughts' three times.", PhoneticGuidance: "Voiceless TH — consistent tongue-between-teeth position", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-050", Name: "The Thatcher Thatched", Description: "TH sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundTH}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'The thatcher thatched the thatched roof thoroughly' clearly.", PhoneticGuidance: "TH at word start — place tongue before speaking", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-051", Name: "Thirty Thousand Boys", Description: "TH sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundTH}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Thirty thousand thoughtful boys thought thoroughly' five times.", PhoneticGuidance: "TH in clusters — don't skip the tongue placement", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-052", Name: "Thick and Thin", Description: "TH sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundTH}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Through thick and thin, the three thought things through' clearly.", PhoneticGuidance: "Short phrase — focus on clean TH each time", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-053", Name: "The Other Mother", Description: "TH sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundTH}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'The other mother and the father gather together' clearly.", PhoneticGuidance: "Voiced TH in 'the', 'other', 'father' — add voice", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-054", Name: "Thin Sticks Thick Bricks", Description: "TH sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundTH}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Thin sticks, thick bricks, thin sticks, thick bricks' at speed.", PhoneticGuidance: "TH vs T contrast — tongue between teeth vs behind teeth", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-055", Name: "This Is the Sixth Zebra", Description: "TH and S contrast twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundTH, domain.SoundS}, Duration: 40 * time.Second, Repetitions: 3, Instructions: "Say 'This is the sixth zebra snoozing thoroughly' three times quickly.", PhoneticGuidance: "TH: tongue between teeth; S: tongue behind teeth", CreatedAt: now, UpdatedAt: now},

		// /sh/ SoundSH — 10 twisters
		{ID: "tt-056", Name: "Sheep Should Sleep", Description: "SH sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundSH}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Sheep should sleep in a shed' five times clearly.", PhoneticGuidance: "Tongue pulled back slightly, lips rounded for SH", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-057", Name: "She Shines Shoes", Description: "SH sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundSH}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'She shines shoes and shoes she shines' five times.", PhoneticGuidance: "SH at word start — lips slightly rounded", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-058", Name: "Shiny Shoes Shine", Description: "SH sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundSH}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Shiny shoes shine on the shelf' five times.", PhoneticGuidance: "SH before different vowels — keep tongue position consistent", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-059", Name: "Shirley Shook Shells", Description: "SH sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundSH}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Shirley shook shells by the shimmering shore' clearly.", PhoneticGuidance: "SH in initial and medial positions — consistent shape", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-060", Name: "Shush the Shy Sheep", Description: "SH sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundSH}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Shush the shy sheep sharing the shade' five times.", PhoneticGuidance: "SH in clusters — maintain lip rounding", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-061", Name: "Shallow Ships Shift", Description: "SH sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundSH}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Shallow ships shift sharply in the shallows' clearly.", PhoneticGuidance: "SH before consonants — don't lose the lip rounding", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-062", Name: "She Sells Shells Swiftly", Description: "SH and S contrast twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundSH, domain.SoundS}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'She sells shells swiftly, so she sells shells swiftly' at speed.", PhoneticGuidance: "Alternate SH and S — tongue moves forward for S", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-063", Name: "Shredded Wheat", Description: "SH sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundSH}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Shredded wheat, shredded wheat, shredded wheat' as fast as possible.", PhoneticGuidance: "SH in consonant cluster — maintain shape through blend", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-064", Name: "Shocking Shaking Shimmering", Description: "SH sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundSH}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Shocking shaking shimmering shadows shift sharply' at speed.", PhoneticGuidance: "Multiple SH sounds — keep each one distinct", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-065", Name: "Freshly Pressed Flesh", Description: "SH sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundSH}, Duration: 40 * time.Second, Repetitions: 3, Instructions: "Say 'Freshly pressed flesh flushes fresh' three times quickly.", PhoneticGuidance: "SH in final position — don't devoice or drop it", CreatedAt: now, UpdatedAt: now},

		// /ch/ SoundCH — 10 twisters
		{ID: "tt-066", Name: "Chester Cheetah", Description: "CH sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundCH}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Chester cheetah chews a chunk of cheap cheddar cheese' clearly.", PhoneticGuidance: "CH is a stop + fricative — tongue tip then blade", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-067", Name: "How Much Wood", Description: "CH sound classic twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundCH}, Duration: 25 * time.Second, Repetitions: 5, Instructions: "Say 'How much wood would a woodchuck chuck if a woodchuck could chuck wood' clearly.", PhoneticGuidance: "CH in 'chuck' and 'woodchuck' — crisp release", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-068", Name: "Charlie Chose Cheese", Description: "CH sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundCH}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Charlie chose cheap cheese chunks cheerfully' five times.", PhoneticGuidance: "CH at word start — build up pressure then release", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-069", Name: "Chop Shops Stock Chops", Description: "CH sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundCH}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Chop shops stock chops, chop shops stock chops' five times.", PhoneticGuidance: "CH in initial and final positions — consistent closure", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-070", Name: "Cheerful Children Chant", Description: "CH sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundCH}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Cheerful children chant cheerfully in the church' clearly.", PhoneticGuidance: "CH before different vowels — same tongue position", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-071", Name: "Cheap Ship Trip", Description: "CH and SH contrast twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundCH, domain.SoundSH}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Cheap ship trip, cheap ship trip' five times quickly.", PhoneticGuidance: "CH: stop then fricative; SH: just fricative", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-072", Name: "Chicken Chasing Cheetahs", Description: "CH sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundCH}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Chicken chasing cheetahs chuckle cheerfully' at speed.", PhoneticGuidance: "Multiple CH sounds — each needs full closure and release", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-073", Name: "Cheeky Chimps Chatter", Description: "CH sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundCH}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Cheeky chimps chatter and chew chunks of chocolate' at speed.", PhoneticGuidance: "CH in clusters — don't reduce to SH under pressure", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-074", Name: "Church Choir Chants", Description: "CH sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundCH}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Church choir chants cheerful choral chunks' quickly.", PhoneticGuidance: "CH in final position — complete the stop release", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-075", Name: "Catch Each Peach", Description: "CH sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundCH}, Duration: 40 * time.Second, Repetitions: 3, Instructions: "Say 'Catch each peach, each peach reach, reach each peach' three times.", PhoneticGuidance: "CH in final position — full affricate, not just SH", CreatedAt: now, UpdatedAt: now},

		// /j/ SoundJ — 10 twisters
		{ID: "tt-076", Name: "Judge Not the Jug", Description: "J sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundJ}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Judge not the jug by its juggle' five times.", PhoneticGuidance: "J is voiced CH — add vocal cord vibration", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-077", Name: "Jolly Juggling Jesters", Description: "J sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundJ}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Jolly juggling jesters juggle joyfully' five times.", PhoneticGuidance: "J at word start — voiced affricate, feel the vibration", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-078", Name: "Jumping Jaguars", Description: "J sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundJ}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Jumping jaguars juggle jelly jars' five times.", PhoneticGuidance: "J before different vowels — same voiced affricate", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-079", Name: "Jerry's Jam Jars", Description: "J sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundJ}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Jerry's jam jars jingle and jangle in January' clearly.", PhoneticGuidance: "J in initial position — consistent voiced closure", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-080", Name: "Joyful Jockeys Jump", Description: "J sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundJ}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Joyful jockeys jump over jumbled jungle gyms' clearly.", PhoneticGuidance: "J in clusters — maintain voicing through the blend", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-081", Name: "Gentle Giant Juggles", Description: "J sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundJ}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'A gentle giant juggles jelly jars in the jungle' clearly.", PhoneticGuidance: "J in medial position — don't reduce to Y sound", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-082", Name: "Jabbering Jays", Description: "J sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundJ}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Jabbering jays jabber and jeer at jaguars' at speed.", PhoneticGuidance: "Multiple J sounds — each needs full voiced closure", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-083", Name: "Jingle Jangle Jungle", Description: "J sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundJ}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Jingle jangle jungle jive, jingle jangle jungle jive' at speed.", PhoneticGuidance: "J in rapid succession — keep each one voiced", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-084", Name: "Jocular Jugglers", Description: "J sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundJ}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Jocular jugglers juggle joyfully in January' quickly.", PhoneticGuidance: "J before different vowels at speed — consistent voicing", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-085", Name: "Huge Gorgeous Gorges", Description: "J sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundJ}, Duration: 40 * time.Second, Repetitions: 3, Instructions: "Say 'Huge gorgeous gorges edge the ageing village' three times.", PhoneticGuidance: "J in medial and final positions — voiced throughout", CreatedAt: now, UpdatedAt: now},

		// /k/ SoundK — 10 twisters
		{ID: "tt-086", Name: "Can You Can a Can", Description: "K sound classic twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundK}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Can you can a can as a canner can can a can' clearly.", PhoneticGuidance: "K at word start — back of tongue contacts soft palate", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-087", Name: "Kick the Bucket", Description: "K sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundK}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Kick the bucket, kick the bucket, kick the bucket' ten times.", PhoneticGuidance: "K in initial and final positions — crisp release", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-088", Name: "Crisp Crackers Crunch", Description: "K sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundK}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Crisp crackers crunch and crackle' five times.", PhoneticGuidance: "K in CR clusters — back of tongue then release", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-089", Name: "Cooks Cook Cupcakes", Description: "K sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundK}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Cooks cook cupcakes quickly in the kitchen' clearly.", PhoneticGuidance: "K in initial and medial positions — consistent closure", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-090", Name: "Clumsy Clowns Clap", Description: "K sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundK}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Clumsy clowns clap and cluck and clatter' clearly.", PhoneticGuidance: "K in CL clusters — back of tongue, then lateral release", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-091", Name: "Quickly Quacking Quails", Description: "K sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundK}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Quickly quacking quails quit the quiet quay' clearly.", PhoneticGuidance: "QU = KW — back of tongue for K, then W rounding", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-092", Name: "Cracked Crackers", Description: "K sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundK}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Cracked crackers crackle and crack in the cracker cracker' at speed.", PhoneticGuidance: "K in clusters and final position — full velar closure", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-093", Name: "Curious Cats Catch", Description: "K sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundK}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Curious cats catch crabs and crackle crackers' at speed.", PhoneticGuidance: "K in multiple positions — consistent back-of-tongue contact", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-094", Name: "Knick Knack Paddywhack", Description: "K sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundK}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Knick knack paddywhack give a dog a bone' at speed.", PhoneticGuidance: "K in final position — don't drop the release", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-095", Name: "Unique Technique", Description: "K sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundK}, Duration: 40 * time.Second, Repetitions: 3, Instructions: "Say 'A unique technique uniquely keeps the creek creek-free' three times.", PhoneticGuidance: "K in medial and final positions — velar closure throughout", CreatedAt: now, UpdatedAt: now},

		// /g/ SoundG — 10 twisters
		{ID: "tt-096", Name: "Good Blood Bad Blood", Description: "G sound classic twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundG}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Good blood, bad blood, good blood, bad blood' five times quickly.", PhoneticGuidance: "G is voiced K — same position, add vocal cord vibration", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-097", Name: "Gobbling Gargoyles", Description: "G sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundG}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Gobbling gargoyles gobble grapes greedily' five times.", PhoneticGuidance: "G at word start — voiced velar stop", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-098", Name: "Green Glass Globes", Description: "G sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundG}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Green glass globes glow greenly' five times.", PhoneticGuidance: "G in GL clusters — voiced back-of-tongue contact", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-099", Name: "Grumpy Gorillas Growl", Description: "G sound beginner twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyBeginner, TargetSounds: []domain.SoundTarget{domain.SoundG}, Duration: 25 * time.Second, Repetitions: 6, Instructions: "Say 'Grumpy gorillas growl and groan in the grove' five times.", PhoneticGuidance: "G in GR clusters — voiced, then liquid R", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-100", Name: "Giggling Geese", Description: "G sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundG}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Giggling geese gaggle and gobble in the garden' clearly.", PhoneticGuidance: "G in initial and medial positions — consistent voicing", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-101", Name: "Gloomy Glowing Globs", Description: "G sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundG}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Gloomy glowing globs of goo glide gracefully' clearly.", PhoneticGuidance: "G in GL clusters — voiced throughout the blend", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-102", Name: "Groggy Frogs Grab Grubs", Description: "G sound intermediate twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyIntermediate, TargetSounds: []domain.SoundTarget{domain.SoundG}, Duration: 30 * time.Second, Repetitions: 5, Instructions: "Say 'Groggy frogs grab grubs greedily in the grass' clearly.", PhoneticGuidance: "G in GR clusters — voiced velar then liquid", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-103", Name: "Gagging Gaggling Geese", Description: "G sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundG}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Gagging gaggling geese gargle and giggle' at speed.", PhoneticGuidance: "Multiple G sounds — each needs full voiced velar closure", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-104", Name: "Gargantuan Gargling Gorillas", Description: "G sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundG}, Duration: 35 * time.Second, Repetitions: 5, Instructions: "Say 'Gargantuan gargling gorillas grab grapes greedily' at speed.", PhoneticGuidance: "G in multiple positions — maintain voicing throughout", CreatedAt: now, UpdatedAt: now},
		{ID: "tt-105", Name: "Gig Bag Egg Nog", Description: "G sound advanced twister", Category: domain.CategoryTongueTwister, Difficulty: domain.DifficultyAdvanced, TargetSounds: []domain.SoundTarget{domain.SoundG}, Duration: 40 * time.Second, Repetitions: 3, Instructions: "Say 'Gig bag egg nog, gig bag egg nog' ten times quickly.", PhoneticGuidance: "G in final position — don't devoice at word end", CreatedAt: now, UpdatedAt: now},
	}
}
