package infrastructure

import (
	"time"

	"speech-practice-app/internal/domain"
)

// seedDictionStrategiesExtended returns diction strategy exercises ds-006 through ds-015.
func seedDictionStrategiesExtended(now time.Time) []domain.Exercise {
	return []domain.Exercise{
		// Clarity focus
		{ID: "ds-006", Name: "Overarticulation Drill", Description: "Exaggerate articulation to build muscle memory for clarity", Category: domain.CategoryDictionStrategy, Difficulty: domain.DifficultyBeginner, Duration: 90 * time.Second, Repetitions: 5, Instructions: "Read aloud: 'The big black bug bled blue-black blood.' Exaggerate every consonant and vowel. Then return to normal speech.", PhoneticGuidance: "Focus area: clarity. Exaggeration trains precise muscle positions.", CreatedAt: now, UpdatedAt: now},
		{ID: "ds-007", Name: "Minimal Pair Clarity", Description: "Use minimal pairs to sharpen sound distinctions", Category: domain.CategoryDictionStrategy, Difficulty: domain.DifficultyIntermediate, Duration: 120 * time.Second, Repetitions: 4, Instructions: "Say these pairs clearly: 'ship/chip', 'thin/tin', 'vine/wine', 'bat/pat'. Listener should hear the difference.", PhoneticGuidance: "Focus area: clarity. Small differences in articulation change meaning.", CreatedAt: now, UpdatedAt: now},
		{ID: "ds-008", Name: "Consonant Cluster Clarity", Description: "Practice consonant clusters for clear speech", Category: domain.CategoryDictionStrategy, Difficulty: domain.DifficultyIntermediate, Duration: 120 * time.Second, Repetitions: 4, Instructions: "Practice: 'strengths', 'twelfths', 'scripts', 'sprints'. Say each word slowly, then at normal speed.", PhoneticGuidance: "Focus area: clarity. Each consonant in a cluster must be articulated.", CreatedAt: now, UpdatedAt: now},
		// Precision focus
		{ID: "ds-009", Name: "Word Ending Precision", Description: "Ensure word endings are fully articulated", Category: domain.CategoryDictionStrategy, Difficulty: domain.DifficultyBeginner, Duration: 90 * time.Second, Repetitions: 5, Instructions: "Read: 'The cats and dogs walked past the old red barn.' Ensure every final consonant is clear — don't drop endings.", PhoneticGuidance: "Focus area: precision. Final consonants are often swallowed in casual speech.", CreatedAt: now, UpdatedAt: now},
		{ID: "ds-010", Name: "Syllable Precision Drill", Description: "Articulate every syllable with equal precision", Category: domain.CategoryDictionStrategy, Difficulty: domain.DifficultyIntermediate, Duration: 120 * time.Second, Repetitions: 4, Instructions: "Say: 'par-tic-u-lar-ly', 'in-ter-est-ing', 'com-for-ta-ble', 'tem-per-a-ture'. Pronounce every syllable.", PhoneticGuidance: "Focus area: precision. Don't reduce unstressed syllables to schwa.", CreatedAt: now, UpdatedAt: now},
		// Volume focus
		{ID: "ds-011", Name: "Projection Practice", Description: "Project voice to fill a room without shouting", Category: domain.CategoryDictionStrategy, Difficulty: domain.DifficultyIntermediate, Duration: 120 * time.Second, Repetitions: 4, Instructions: "Imagine speaking to someone 10 metres away. Say: 'Good morning, everyone. Today we will discuss an important topic.' Project without straining.", PhoneticGuidance: "Focus area: volume. Projection comes from breath support, not throat tension.", CreatedAt: now, UpdatedAt: now},
		{ID: "ds-012", Name: "Dynamic Volume Range", Description: "Practice speaking across a wide volume range", Category: domain.CategoryDictionStrategy, Difficulty: domain.DifficultyAdvanced, Duration: 120 * time.Second, Repetitions: 3, Instructions: "Read a passage starting at a whisper, gradually increasing to full projection, then back to whisper. Maintain clarity throughout.", PhoneticGuidance: "Focus area: volume. Clarity must be maintained at all volume levels.", CreatedAt: now, UpdatedAt: now},
		// Resonance focus
		{ID: "ds-013", Name: "Chest Resonance Activation", Description: "Develop chest resonance for a richer, fuller voice", Category: domain.CategoryDictionStrategy, Difficulty: domain.DifficultyBeginner, Duration: 90 * time.Second, Repetitions: 5, Instructions: "Place hand on chest. Say 'mmm' on a low pitch until you feel vibration. Then speak: 'My voice resonates deeply.' Feel the chest vibration.", PhoneticGuidance: "Focus area: resonance. Lower pitch activates chest resonance.", CreatedAt: now, UpdatedAt: now},
		{ID: "ds-014", Name: "Forward Resonance Placement", Description: "Place voice forward in the mouth for brightness", Category: domain.CategoryDictionStrategy, Difficulty: domain.DifficultyIntermediate, Duration: 120 * time.Second, Repetitions: 4, Instructions: "Say 'mee-may-mah-moh-moo' feeling vibration on your lips. Then speak a sentence keeping that forward placement.", PhoneticGuidance: "Focus area: resonance. Forward placement creates a brighter, more carrying tone.", CreatedAt: now, UpdatedAt: now},
		// Breath control focus
		{ID: "ds-015", Name: "Sustained Phrase Breathing", Description: "Control breath to sustain long phrases without gasping", Category: domain.CategoryDictionStrategy, Difficulty: domain.DifficultyAdvanced, Duration: 150 * time.Second, Repetitions: 3, Instructions: "Take one breath and say: 'The quick brown fox jumps over the lazy dog and then runs back to the beginning of the sentence.' Don't gasp mid-phrase.", PhoneticGuidance: "Focus area: breath control. Breathe at natural phrase boundaries, not mid-word.", CreatedAt: now, UpdatedAt: now},
	}
}

// seedPacingStrategiesExtended returns pacing strategy exercises ps-006 through ps-015.
func seedPacingStrategiesExtended(now time.Time) []domain.Exercise {
	return []domain.Exercise{
		// Pause placement focus
		{ID: "ps-006", Name: "Dramatic Pause Technique", Description: "Use strategic pauses for emphasis and impact", Category: domain.CategoryPacingStrategy, Difficulty: domain.DifficultyIntermediate, Duration: 120 * time.Second, Repetitions: 4, Instructions: "Read: 'And then... everything changed.' Pause for 2 full seconds before 'everything'. Notice the dramatic effect.", PhoneticGuidance: "Focus area: pause placement. Silence before a key word amplifies its impact.", CreatedAt: now, UpdatedAt: now},
		{ID: "ps-007", Name: "Breath Pause Naturalisation", Description: "Make pauses feel natural rather than hesitant", Category: domain.CategoryPacingStrategy, Difficulty: domain.DifficultyBeginner, Duration: 90 * time.Second, Repetitions: 5, Instructions: "Read a paragraph and pause only at punctuation marks. Breathe during pauses. Avoid filler words like 'um' and 'uh'.", PhoneticGuidance: "Focus area: pause placement. Pauses at punctuation feel natural to listeners.", CreatedAt: now, UpdatedAt: now},
		{ID: "ps-008", Name: "Pause for Comprehension", Description: "Pause after complex ideas to aid listener comprehension", Category: domain.CategoryPacingStrategy, Difficulty: domain.DifficultyIntermediate, Duration: 120 * time.Second, Repetitions: 4, Instructions: "Explain a complex concept. After each main point, pause for 1-2 seconds. Let the idea land before continuing.", PhoneticGuidance: "Focus area: pause placement. Pauses give listeners time to process information.", CreatedAt: now, UpdatedAt: now},
		// Syllable timing focus
		{ID: "ps-009", Name: "Metronome Speech", Description: "Use a metronome to develop consistent syllable timing", Category: domain.CategoryPacingStrategy, Difficulty: domain.DifficultyBeginner, Duration: 120 * time.Second, Repetitions: 3, Instructions: "Set a metronome to 80 BPM. Speak one syllable per beat: 'The-quick-brown-fox-jumps-o-ver-the-la-zy-dog.' Then try 100 BPM.", PhoneticGuidance: "Focus area: syllable timing. Consistent timing creates a steady, confident rhythm.", CreatedAt: now, UpdatedAt: now},
		{ID: "ps-010", Name: "Isochronous Rhythm Drill", Description: "Practice stress-timed rhythm of English", Category: domain.CategoryPacingStrategy, Difficulty: domain.DifficultyAdvanced, Duration: 120 * time.Second, Repetitions: 4, Instructions: "Say these at the same speed: 'Cats eat fish.' / 'The cats are eating the fish.' / 'The cats have been eating all the fish.' Each should take the same time.", PhoneticGuidance: "Focus area: syllable timing. English is stress-timed — stressed syllables occur at regular intervals.", CreatedAt: now, UpdatedAt: now},
		// Phrase grouping focus
		{ID: "ps-011", Name: "Thought Group Chunking", Description: "Group words into meaningful thought units", Category: domain.CategoryPacingStrategy, Difficulty: domain.DifficultyIntermediate, Duration: 120 * time.Second, Repetitions: 4, Instructions: "Mark thought groups with slashes: 'The man / who lives next door / has a dog / that barks all night.' Read each group as one unit.", PhoneticGuidance: "Focus area: phrase grouping. Thought groups help listeners parse meaning.", CreatedAt: now, UpdatedAt: now},
		{ID: "ps-012", Name: "Linking Words in Phrases", Description: "Link words within phrases for smooth delivery", Category: domain.CategoryPacingStrategy, Difficulty: domain.DifficultyIntermediate, Duration: 120 * time.Second, Repetitions: 4, Instructions: "Say 'an apple' as 'a-napple', 'turn off' as 'tur-noff'. Practice linking final consonants to initial vowels within phrases.", PhoneticGuidance: "Focus area: phrase grouping. Linking creates natural, fluent speech flow.", CreatedAt: now, UpdatedAt: now},
		// Emphasis patterns focus
		{ID: "ps-013", Name: "Contrastive Stress Drill", Description: "Use stress to contrast and clarify meaning", Category: domain.CategoryPacingStrategy, Difficulty: domain.DifficultyIntermediate, Duration: 120 * time.Second, Repetitions: 4, Instructions: "Say 'I didn't say SHE stole it' (someone else did). Then 'I didn't say she STOLE it' (she did something else). Notice how stress changes meaning.", PhoneticGuidance: "Focus area: emphasis patterns. Stress on different words changes the implied meaning.", CreatedAt: now, UpdatedAt: now},
		{ID: "ps-014", Name: "New Information Stress", Description: "Stress new information, not given information", Category: domain.CategoryPacingStrategy, Difficulty: domain.DifficultyAdvanced, Duration: 120 * time.Second, Repetitions: 4, Instructions: "Q: 'What did John buy?' A: 'John bought a CAR.' Q: 'Who bought a car?' A: 'JOHN bought a car.' Stress the new information each time.", PhoneticGuidance: "Focus area: emphasis patterns. New information carries the main stress in a sentence.", CreatedAt: now, UpdatedAt: now},
		{ID: "ps-015", Name: "Pitch Accent for Emphasis", Description: "Use pitch changes to mark emphasis", Category: domain.CategoryPacingStrategy, Difficulty: domain.DifficultyAdvanced, Duration: 120 * time.Second, Repetitions: 3, Instructions: "Read: 'This is REALLY important.' Raise pitch on 'really'. Then: 'This is really IMPORTANT.' Raise pitch on 'important'. Notice the different emphasis.", PhoneticGuidance: "Focus area: emphasis patterns. Pitch rise on a word signals it carries the main message.", CreatedAt: now, UpdatedAt: now},
	}
}
